name: CI

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - name: Fetch base branch
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run:
          git fetch --no-tags --prune --depth=1 origin
          +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
      - run: yarn
      - uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          build-script: yarn build
          bundlewatch-config: .bundlewatch.config.js
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
#
# https://github.com/actions/checkout/issues/93
# https://github.com/actions/checkout/pull/155
