name: PR

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          bundlewatch-config: .bundlewatch.config.js
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
